apiVersion : apps/v1
kind: Deployment
metadata:
  name: "randomquotecluster-4f85"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "randomquotecluster-4f85"
  template:
    metadata:
      labels:
        app: "randomquotecluster-4f85"
    spec:
      containers:
        - name: "randomquotecluster-4f85"
          image: "randomquote.azurecr.io/randomquotecluster"
          ports:
          - containerPort: 80