apiVersion: v1
kind: Service
metadata:
    name: "randomquotecluster-4f85"
    labels:
        app: "randomquotecluster-4f85"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "randomquotecluster-4f85"